from enum import Enum


class EPLTeam(Enum):
    ARSENAL = "Arsenal"
    ASTON_VILLA = "Aston Villa"
    BRENTFORD = "Brentford"
    BRIGHTON_AND_HOVE_ALBION = "Brighton & Hove Albion"
    CHELSEA = "Chelsea"
    CRYSTAL_PALACE = "Crystal Palace"
    EVERTON = "Everton"
    FULHAM = "Fulham"
    LEEDS_UNITED = "Leeds United"
    LEICESTER_CITY = "Leicester City"
    LIVERPOOL = "Liverpool"
    MANCHESTER_CITY = "Manchester City"
    MANCHESTER_UNITED = "Manchester United"
    NEWCASTLE_UNITED = "Newcastle United"
    NOTTINGHAM_FOREST = "Nottingham Forest"
    SOUTHAMPTON_FC = "Southampton FC"
    TOTTENHAM_HOTSPUR = "Tottenham Hotspur"
    WEST_HAM_UNITED = "West Ham United"
    WOLVERHAMPTON_WANDERERS = "Wolverhampton Wanderers"
    AFC_BOURNEMOUTH = "AFC Bournemouth"
    IPSWICH_TOWN = "Ipswich Town"
