from enum import Enum


class NHLTeam(Enum):
    ANAHEIM_DUCKS = "Anaheim Ducks"
    ARIZONA_COYOTES = "Arizona Coyotes"
    BOSTON_BRUINS = "Boston Bruins"
    BUFFALO_SABRES = "Buffalo Sabres"
    CALGARY_FLAMES = "Calgary Flames"
    CAROLINA_HURRICANES = "Carolina Hurricanes"
    CHICAGO_BLACKHAWKS = "Chicago Blackhawks"
    COLORADO_AVALANCHE = "Colorado Avalanche"
    COLUMBUS_BLUE_JACKETS = "Columbus Blue Jackets"
    DALLAS_STARS = "Dallas Stars"
    DETROIT_RED_WINGS = "Detroit Red Wings"
    EDMONTON_OILERS = "Edmonton Oilers"
    FLORIDA_PANTHERS = "Florida Panthers"
    LOS_ANGELES_KINGS = "Los Angeles Kings"
    MINNESOTA_WILD = "Minnesota Wild"
    MONTREAL_CANADIENS = "Montreal Canadiens"
    NASHVILLE_PREDATORS = "Nashville Predators"
    NEW_JERSEY_DEVILS = "New Jersey Devils"
    NEW_YORK_ISLANDERS = "New York Islanders"
    NEW_YORK_RANGERS = "New York Rangers"
    OTTAWA_SENATORS = "Ottawa Senators"
    PHILADELPHIA_FLYERS = "Philadelphia Flyers"
    PITTSBURGH_PENGUINS = "Pittsburgh Penguins"
    SAN_JOSE_SHARKS = "San Jose Sharks"
    SEATTLE_KRAKEN = "Seattle Kraken"
    ST_LOUIS_BLUES = "St. Louis Blues"
    TAMPA_BAY_LIGHTNING = "Tampa Bay Lightning"
    TORONTO_MAPLE_LEAFS = "Toronto Maple Leafs"
    UTAH_HOCKEY_CLUB = "Utah Hockey Club"
    VANCOUVER_CANUCKS = "Vancouver Canucks"
    VEGAS_GOLDEN_KNIGHTS = "Vegas Golden Knights"
    WASHINGTON_CAPITALS = "Washington Capitals"
    WINNIPEG_JETS = "Winnipeg Jets"
